runtime: python27
api_version: 1
threadsafe: true

handlers:

# - url: /admin/.*
#   script: $PYTHON_LIB/google/appengine/ext/admin
#   login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: phone_home.application

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: "latest"
- name: boto
  version: "latest"
# [END libraries]
